# Site settings
name: GoDaddy Open Source Center
email: opensource@godaddy.com
description: > # this means to ignore newlines until the next key
  Information from our engineering team about the technology and tools we
  use to create software which empowers small businesses around the world
  to build and market their digital identities.
url: "https://godaddy.github.io"

twitter_username: GodaddyOSS
github_username:  godaddy
analytics_id: UA-37178807-20

permalink: pretty

plugins:
  - jekyll-sitemap

sass:
  sass_dir: ./_stylesheets
  style: compressed

applicant_source: APPLICANT_SOURCE-3-119
